#!/bin/sh
# Usage: gen_boot_layout.sh stage1_bin > boot_layout.inc
#
# Computes how many sectors stage 1 occupies so the VBR can:
#   - Reserve enough sectors in the BPB (BPB_RsvdSecCnt = 1 + STAGE1_SECTORS)
#   - Know where stage 1 lives (STAGE1_REL_LBA = 1)

set -e

stage1="$1"

if [ ! -f "$stage1" ]; then
    echo "usage: $0 stage1_bin" >&2
    exit 1
fi

# Get size in bytes
stage1_size=$(wc -c < "$stage1")

# Compute sectors
stage1_secs=$(( (stage1_size + 511) / 512 ))

cat <<EOF
; Auto-generated by gen_boot_layout.sh - DO NOT EDIT.
; Stage sizes / LBAs relative to partition start.

STAGE1_REL_LBA   equ 1
STAGE1_SECTORS   equ $stage1_secs
EOF