#!/bin/sh
# Usage: gen_boot_layout.sh stage1_bin stage2_bin > boot_layout.inc

set -e

stage1="$1"
stage2="$2"

if [ ! -f "$stage1" ] || [ ! -f "$stage2" ]; then
    echo "usage: $0 stage1_bin stage2_bin" >&2
    exit 1
fi

# Get sizes in bytes
stage1_size=$(wc -c < "$stage1")
stage2_size=$(wc -c < "$stage2")

# Compute sectors
stage1_secs=$(( (stage1_size + 511) / 512 ))
stage2_secs=$(( (stage2_size + 511) / 512 ))

cat <<EOF
; Auto-generated by gen_boot_layout.sh - DO NOT EDIT.
; Stage sizes / LBAs relative to partition start.

STAGE1_REL_LBA   equ 1
STAGE1_SECTORS   equ $stage1_secs

STAGE2_REL_LBA   equ (STAGE1_REL_LBA + STAGE1_SECTORS)
STAGE2_SECTORS   equ $stage2_secs
EOF